Repository iov-one/weave, pull requests merged in 2019-07, with the labels that each got.

#859 weave/store: iterator tests added
  store/iterator.go
  store/iterator_test.go
Labels: Launch, bug

#865 x/username: change address type from []byte to string
  CHANGELOG.md
  cmd/bnscli/clitests/register_username.test.gold
  cmd/bnscli/cmd_username.go
  cmd/bnsd/app/examples.go
  cmd/bnsd/scenarios/username_test.go
  cmd/bnsd/x/username/codec.pb.go
  cmd/bnsd/x/username/codec.proto
  cmd/bnsd/x/username/handlers_test.go
  cmd/bnsd/x/username/init_test.go
  cmd/bnsd/x/username/model_test.go
  cmd/bnsd/x/username/msg_test.go
  docs/proto/index.html
  spec/gogo/cmd/bnsd/x/username/codec.proto
  spec/proto/cmd/bnsd/x/username/codec.proto
  spec/testvectors/username_change_token_targets_msg.json
  spec/testvectors/username_register_token_msg.json
  spec/testvectors/username_register_token_tx.json
Labels: Launch

#873 Feature/launch owner idx
  CHANGELOG.md
  cmd/bnsd/x/username/model.go
  cmd/bnsd/x/username/model_test.go
Labels: Launch

#877 Feature/empty targets
  CHANGELOG.md
  cmd/bnsd/x/username/handlers_test.go
  cmd/bnsd/x/username/model.go
  cmd/bnsd/x/username/model_test.go
  cmd/bnsd/x/username/msg_test.go
Labels: Launch

#879 aswap: rename ReturnMsg
  cmd/bnsd/app/codec.pb.go
  cmd/bnsd/app/codec.proto
  docs/proto/index.html
  spec/gogo/cmd/bnsd/app/codec.proto
  spec/gogo/x/aswap/codec.proto
  spec/proto/cmd/bnsd/app/codec.proto
  spec/proto/x/aswap/codec.proto
  x/aswap/codec.pb.go
  x/aswap/codec.proto
  x/aswap/handler.go
  x/aswap/handler_test.go
  x/aswap/msg.go
  x/aswap/msg_test.go
Labels: Launch

#884 remove tmlibs import
  cmd/bnsd/client/client.go
  go.mod
  go.sum
Labels: bug

#919 store/iavl: fix iterator race condition
  store/iavl/iterator.go
  store/iavl/iterator_test.go
Labels: bug

#909 bnsd/username: allow for only iov domain
  CHANGELOG.md
  cmd/bnsd/x/username/username.go
  cmd/bnsd/x/username/username_test.go
Labels: bug
